#####################
### MISCELLANEOUS ###
#####################
seed: 42 # Random seed
dev: False
slurm_log_path: /project/def-lulam50/magod/rl_summ/slurm_outputs/

##################
### MODEL ARGS ###
##################
model: "banditsum_mcts" # One of ['lead3', 'banditsum', 'banditsum_mcts', 'a2c']
train_batch_size: 64
test_batch_size: 256
hidden_dim: 200
decoder_dim: 100
n_repeats_per_sample: 16
learning_rate: 0.000001
epsilon: 0.1
n_sents_per_summary: 3

####################
### DATASET ARGS ###
####################
dataset: "cnn_dailymail" # One of ['cnn_dailymail']
data_path: "/scratch/magod/summarization_datasets/cnn_dailymail/data/" # Argument to the Dataset object
embeddings: "glove.6B.100d"
embeddings_location: "/scratch/magod/embeddings/"
sets: "train-val-test" # If present, 'train' must be first

###################
### REWARD ARGS ###
###################
reward: "rouge" # One of ['rouge']
rouge_base_path: "/scratch/magod/summarization_datasets/cnn_dailymail/data/rouge_npy/"

##################
### MCTS ARGS  ###
##################
c_puct: 0.5
n_mcts_samples: 50

####################
### TRAINER ARGS ###
####################
trainer: "pl" # One of ['gradient_free', 'pl']
gradient_clip_val: 1
gpus: 1
overfit_pct: 0.0
fast_dev_run: False
distributed_backend: "dp" # one of ['dp', 'ddp', 'ddp2']
use_amp: False
print_nan_grads: True
val_check_interval: 0.1
default_save_path: "/project/def-lulam50/magod/rl_summ/exp_logging/results/"
weights_save_path: "/project/def-lulam50/magod/rl_summ/exp_logging/weight_saving"
max_epochs: 4
