#####################
### MISCELLANEOUS ###
#####################
seed: 42 # Random seed
dev: False
slurm_log_path: /project/def-lulam50/magod/rl_summ/slurm_outputs/

##################
### MODEL ARGS ###
##################
model: "linsit" # One of ['lead3', 'banditsum', 'banditsum_mcts', 'rlsum_mcts', 'azsum_mcts', 'a2c', 'rlsum_oh']
train_batch_size: 64
test_batch_size: 64
hidden_dim: 200
decoder_dim: 100
n_repeats_per_sample: 16
learning_rate: 0.0001
epsilon: 0.1
n_sents_per_summary: 3
n_jobs_for_mcts: 8
tau: 10.0

####################
### DATASET ARGS ###
####################
dataset: "cnn_dailymail" # One of ['cnn_dailymail']
data_path: "$SLURM_TMPDIR/linsit_dataset" # Argument to the Dataset object
embeddings: "glove.6B.100d"
embeddings_location: "/scratch/magod/embeddings/"
sets: "train-val-test" # If present, 'train' must be first

###################
### REWARD ARGS ###
###################
reward: "rouge" # One of ['rouge']

#################
### UCB ARGS  ###
#################
c_puct: 100000000 # 10 ** 8
ucb_sampling: "linear" # One of ["fix", "linear"]

####################
### TRAINER ARGS ###
####################
trainer: "pl" # One of ['gradient_free', 'pl']
gradient_clip_val: 1
gpus: -1
overfit_pct: 0.0
fast_dev_run: False
distributed_backend: "dp" # one of ['dp', 'ddp', 'ddp2']
val_check_interval: 0.1
default_save_path: "/project/def-lulam50/magod/rl_summ/exp_logging/real_final_results/"
weights_save_path: "/project/def-lulam50/magod/rl_summ/exp_logging/new_weight_saving/"
max_epochs: 5
weight_decay: 0.000001
dropout: 0.0
accumulate_grad_batches: 1
